//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdithTour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdithTourEntities : DbContext
    {
        public EdithTourEntities()
            : base("name=EdithTourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Airline> Airline { get; set; }
        public virtual DbSet<Combo> Combo { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Customer_Level> Customer_Level { get; set; }
        public virtual DbSet<Data_market> Data_market { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Orderdetails> Orderdetails { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Ticket_Combo> Ticket_Combo { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Tour_Inside> Tour_Inside { get; set; }
        public virtual DbSet<Tour_Outside> Tour_Outside { get; set; }
        public virtual DbSet<Tourtrending> Tourtrending { get; set; }
    }
}
